apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jaipro
  labels:
    run: keycloak
    environment: dev
  name: keycloak
spec:
  selector:
    matchLabels:
      run: keycloak
  template:
    metadata:
      labels:
        run: keycloak
    spec:
      containers:
        - image: jboss/keycloak:16.1.0
          name: keycloak
          ports:
            - containerPort: 8080
          env:
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: 104.197.90.97
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: keycloak.db.user
                  name: keycloak-credentials
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keycloak.db.pwd
                  name: keycloak-credentials
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  key: keycloak.user
                  name: keycloak-credentials
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keycloak.user.pwd
                  name: keycloak-credentials
            - name: KEYCLOAK_LOGLEVEL
              value: INFO
            - name: WILDFLY_LOGLEVEL
              value: INFO
      dnsPolicy: ClusterFirst
      restartPolicy: Always