apiVersion: v1
kind: Secret
metadata:
  namespace: jaipro
  name: keycloak-credentials
data:
  keycloak.db.pwd: Z0wlY31WdkcuRkl6Vj4lSQ==
  keycloak.db.user: YXBwa2V5Y2xvYWs=
  keycloak.user: YWRtaW4=
  keycloak.user.pwd: YWRtaW4=