apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: keycloak-quay
  labels:
    run: keycloak-quay
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30021
  selector:
    run: keycloak-quay
  type: LoadBalancer
status:
  loadBalancer: {}