apiVersion: v1
kind: Service
metadata:
  name: jaipro-keycloak
  namespace: jaipro
spec:
  type: NodePort
  ports:
    - targetPort: 8090
      port: 8080
      protocol: TCP
  selector:
    service: jaipro-keycloak
    type: backend